# Generated by Django 3.2.4 on 2021-06-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210604_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
    ]
